namespace VRPTWOptimizer
{
    /// <summary>
    /// Description of TransportRequest insert consequences
    /// </summary>
    public class InsertionResult
    {
        /// <summary>
        /// Time when we will arrive to serve inserted TransportRequest
        /// </summary>
        public double ExpectedArriveTime { get; }
        /// <summary>
        /// Max delay generated by insertion of TransportRequest
        /// </summary>
        public double MaxDelay { get; }
        /// <summary>
        /// Route length added by insertion of TransportRequest
        /// </summary>
        public double NewAddedDistance { get; }
        public double NewNextArriveTime { get; }

        public double OldDistanceBetween { get; }

        public double OldNextArriveTime { get; }

        public bool Success { get; }

        public InsertionResult(
            double oldDistanceBetween,
            double newAddedDistance,
            double oldNextArriveTime,
            double newNextArriveTime,
            double expectedArriveTime,
            double maxDelay,
            bool success)
        {
            OldDistanceBetween = oldDistanceBetween;
            OldNextArriveTime = oldNextArriveTime;
            NewNextArriveTime = newNextArriveTime;
            ExpectedArriveTime = expectedArriveTime;
            Success = success;
            NewAddedDistance = newAddedDistance;
            MaxDelay = maxDelay;
        }
    }
}